### ISSUE TITLE
VolumeControl is not defined

### ISSUE THREAD

**Issue by pareta2** [manusimpson/Phonegap-Android-VolumeControl#3]
Hello 
I am using this plugin in appery io but everytime i am getting VolumeControl is not defined.

**Comment by manusimpson** [comment]
Hi Shubham, this plugin is obssolete since I did it for an old version of
phonegap. I don't remember exactly which but was around 1.x
What are you developing? Maybe there are another plugin useful for you.


---
Manuel Simpson
Cel. +549 - 2954 - 15442487

**Comment by manusimpson** [comment]
I have updated the plugin.
