### ISSUE TITLE
“Phonegap-Android-VolumeControl” Unable to install

### ISSUE THREAD

**Issue by zhengyanhu** [manusimpson/Phonegap-Android-VolumeControl#7]
I can't install this plugin. It prompts me that I am missing the package.json file.
Can you join the version that provides the IOS platform?

**Comment by manusimpson** [comment]
I did it for an Android project, many time ago. Not iOS

**Comment by zhengyanhu** [comment]
I tried to write code for an IOS platform, and fortunately it worked, though it was simpler
